# Numpy

Program on Numpy,

In [1]:
import numpy as np
print(np.__version__)

1.25.1


#0D Array

In [2]:
a=np.array(10)
a

array(10)

#1D Array

In [3]:
a=np.array([1,0])
a

array([1, 0])

#2D Array

In [4]:
a=np.array([[1,0],[3,0]])
print(a)

[[1 0]
 [3 0]]


#3D Array

In [5]:
a=np.array([[[1,0],[3,0]],[[2,0],[4,0]]])
print(a)

[[[1 0]
  [3 0]]

 [[2 0]
  [4 0]]]


Array's with All Dimension

ndmin=5

In [2]:
import numpy as np

print(np.array(10)) #0D

print(np.array([1,0])) #1D

print(np.array([[1,0],[3,0]])) #2D

print(np.array([ [ [1,0],[3,0] ],[ [2,0],[4,0] ] ])) #3D

10
[1 0]
[[1 0]
 [3 0]]
[[[1 0]
  [3 0]]

 [[2 0]
  [4 0]]]


In [12]:
# specifies the minimum dimensions of resultant array.
a=np.array([[1,2],[3,4],[5,6]],ndmin=10)
print(a)


[[[[[[[[[[1 2]
         [3 4]
         [5 6]]]]]]]]]]


numpy.ndarray.ndim() function return the number of dimensions of an array.

In [34]:
a=np.array([[1,2],[3,4],[5,6]])
print(a.ndim)

2


shape( )returns a tuple with each index having the number of corresponding elements.

Array Attributes

In [5]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
# Get the Shape of an Array 
print(a.ndim)

# Get the Shape of an Array
print(a.shape)

# Get the Datatype of an Array 
print(a.dtype)

# Get the total number of an element in an array
print(a.size)

 

2
(2, 5)
int32
10


In [9]:
# returns an integer that tells us how many dimensions the array have.

a=np.array([[[1,2,3,4,5]],[[6,7,8,9,10]]])

print(a.ndim) # get the dimension of an array
print(a.shape)
print(a)

3
(2, 1, 5)
[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


Filling array's with auto element

In [12]:
import numpy as np

# returns a new array of given shape and type, where the element's value as 0.
print(np.zeros(4))
print(np.zeros([4,12]))  

# returns a new array of given shape and data type, where the element's value is set to 1
print(np.ones([4,4]))

# one of the array creation routines based on numerical ranges
print(np.arange(4,100,2))  

# if we want upto 20 we should give 10 to 21 
print(np.arange(10,21))



[0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50
 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98]
[10 11 12 13 14 15 16 17 18 19 20]


Sorting Array's

In [13]:
import numpy as np

# using sort function() in numpy to set in order
print(np.sort((1,3,5,7,9,2,4,6,8,10))) 

#  sort with using string (alphabetical)
print(np.sort(("B","E","C","D",'A')))

#  sorting 2D dimension 
a=np.array([[3,2,1],[6,5,4]])
print(np.sort(a))



[ 1  2  3  4  5  6  7  8  9 10]
['A' 'B' 'C' 'D' 'E']
[[1 2 3]
 [4 5 6]]


Access Array element

In [4]:
import numpy as np

a=np.array([1,2,3,4,5])
print(a[2])

data=np.array([1,2,3,4,5,6,7,8,9,10])

print(data[1])    # picking value from index

print(data[1:])   # skiping first value and printing all values from list

print(data[0:8])  # printing whole list

print(data[-2:])  # printing values from revers order

print(data[-5:-2])



3
2
[ 2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7 8]
[ 9 10]
[6 7 8]


In [52]:
# picking the paticular value from matrix by using (row,coloum) 
# 2D
matrix=np.array([[10,20,41,51,61],[30,40,12,45,78]])
print(matrix)
print(matrix[1,0])
        # (Row,Coloum)  

# 3D
matrix=np.array([[[10,20,41,51,61]],[[30,40,12,45,78]]])
print(matrix)

print(matrix[1,0,0])



[[10 20 41 51 61]
 [30 40 12 45 78]]
30
[[[10 20 41 51 61]]

 [[30 40 12 45 78]]]
30


In [56]:
# slicing array with 3D
matrix=np.array([[[1,2,3],[4,5,6]],[[7,8,9,],[10,11,12]]])
print(matrix)

print(matrix[0,1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
5


In [58]:
# slicing with array

a=np.array([[10,20,41,51,61],[30,40,12,45,78]])
print(a[0,1:4])


[20 41 51]


where()

In [65]:
import numpy as np

arr=np.array([1,2,40,15,40,18,40])
x=np.where(arr==40)# condition to print index value where the reapeted values are present
print(x)

a=np.array([1,2,3,4,5,6,7,8])
y=np.where(a%4==0) # condition to divisable with 4 and get remainder=0 thn print the index value (number) from list
print(y)



(array([2, 4, 6], dtype=int64),)
(array([3, 7], dtype=int64),)


searchsorted

In [71]:
import numpy as np

a=np.array([6,7,8,19])
x=np.searchsorted(a,9)
print(x)

print(np.searchsorted([1,2,3,4],3)) #

print(np.searchsorted([1,2,3,4],5 ,side='right'))

print(np.searchsorted([1,2,3,4],[-10,10,2,6]))


3
2
4
4
[0 4 1 4]


 Array Reshaping

In [48]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

# Reshape Any Array
x=a.reshape(4,3)
print(x)

# Flatten to An Array (Convert to 1D)
Flatten=a.flatten()
print(Flatten)

# Traspose Any Array
Transpose=a.T
print(Transpose)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


Filtering Array

In [3]:
import numpy as np

ar=np.array([1,2,3,4])

x=[True,False,True,False]
newarr=ar[x]
print(newarr)


[1 3]


In [4]:
gou=[0,1,2,3,4,5,6,7,8,9,10]
#  filtering of odd number
result=filter(lambda x:x%2!=0,gou)
print(list(result))

#  filtering of even number 
result=filter(lambda x:x%2==0,gou)
print(list(result))

[1, 3, 5, 7, 9]
[0, 2, 4, 6, 8, 10]


Concantenate

In [15]:
import numpy as np

#  1st matrix
a=np.arange(12).reshape(4,3)
print("A:",a)

#  2nd matrix
b=np.arange(11,23).reshape(4,3)
print("B:",b)

#  3rd matrix
c=np.arange(23,35).reshape(4,3)
print("C:",c)

result=np.concatenate((a,b,c))

print("answere:",result)

A: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
B: [[11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
C: [[23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]]
answere: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]]


Concantenate( )

In [16]:
#  Axis .
np.concatenate((a,b,c),axis=1)

array([[ 0,  1,  2, 11, 12, 13, 23, 24, 25],
       [ 3,  4,  5, 14, 15, 16, 26, 27, 28],
       [ 6,  7,  8, 17, 18, 19, 29, 30, 31],
       [ 9, 10, 11, 20, 21, 22, 32, 33, 34]])

Stack( )

In [7]:
#  Stack: stack() is used for joining multiple NumPy arrays
np.stack((a,b,c),axis=1)

array([[[ 0,  1,  2],
        [11, 12, 13],
        [23, 24, 25]],

       [[ 3,  4,  5],
        [14, 15, 16],
        [26, 27, 28]],

       [[ 6,  7,  8],
        [17, 18, 19],
        [29, 30, 31]],

       [[ 9, 10, 11],
        [20, 21, 22],
        [32, 33, 34]]])

Vstack( )

In [17]:
#  Vstack:vstack() function is used to stack the sequence of NumPy arrays vertically and return the single array.
np.vstack((a,b,c))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [23, 24, 25],
       [26, 27, 28],
       [29, 30, 31],
       [32, 33, 34]])

hstack( )

In [18]:
#  hstack:hstack() function is used to stack the sequence of input arrays horizontally 
# (i.e. column wise) to make a single array.
np.hstack((a,b,c))

array([[ 0,  1,  2, 11, 12, 13, 23, 24, 25],
       [ 3,  4,  5, 14, 15, 16, 26, 27, 28],
       [ 6,  7,  8, 17, 18, 19, 29, 30, 31],
       [ 9, 10, 11, 20, 21, 22, 32, 33, 34]])

dstack( )

In [20]:
import numpy as np

# dstack:The dstack() function in NumPy is used to stack or arrange the given arrays
#  in a sequence depth wise
arr=np.dstack((a,b,c))
print(arr[1,0,1])
print(arr)

14
[[[ 0 11 23]
  [ 1 12 24]
  [ 2 13 25]]

 [[ 3 14 26]
  [ 4 15 27]
  [ 5 16 28]]

 [[ 6 17 29]
  [ 7 18 30]
  [ 8 19 31]]

 [[ 9 20 32]
  [10 21 33]
  [11 22 34]]]


Array Slicing And Indexing

In [51]:
import numpy as np

Array=np.array([[1,2,3],[4,5,6],[7,8,9]])

# Access Individual Element  in [index,row] method
index=Array[0,0]
print(index)

# Access paticular Row
Row=(Array[1])
print(Row)

# Access paticular Coloumn
Coloumn=(Array[:,1])
print(Coloumn)

#  Subarray
SubAry=Array[0:2,1:3]
print(SubAry)

1
[4 5 6]
[2 5 8]
[[2 3]
 [5 6]]


Array opration

In [3]:
import numpy as np

Op_Array1=np.array([[1,2,3],[4,5,6],[2,5,6]])

Op_Array2=np.array([[4,5,6],[7,8,9],[3,4,7]])

Sum=Op_Array1+Op_Array2
print("sum",Sum)

Subtraction=Op_Array1-Op_Array2
print("Subtraction",Subtraction)

Mutiplication=Op_Array1*Op_Array2
print("Mutiplication",Mutiplication)

Division=Op_Array1/Op_Array2
print("Division",Division)

# Dot Product
Dot_Product=np.dot(Op_Array1,Op_Array2)
print("Dot_Product",Dot_Product)


sum [[ 5  7  9]
 [11 13 15]
 [ 5  9 13]]
Subtraction [[-3 -3 -3]
 [-3 -3 -3]
 [-1  1 -1]]
Mutiplication [[ 4 10 18]
 [28 40 54]
 [ 6 20 42]]
Division [[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [0.66666667 1.25       0.85714286]]
Dot_Product [[ 27  33  45]
 [ 69  84 111]
 [ 61  74  99]]


In [78]:
# Element Wise mathematatical function
exp=np.exp(Op_Array1)
print(exp)


[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]
 [  7.3890561  148.4131591  403.42879349]]


In [4]:
# import numpy as np
# Statistical Function

Mean=np.mean(Op_Array1)
print("Mean",Mean)
Median=np.median(Op_Array1)
print("Median",Median)
Std_dev=np.std(Op_Array1)
print("Std_dev",Std_dev)

Mean 3.7777777777777777
Median 4.0
Std_dev 1.7497795275581802
