Opencv

OpenCV is a Python library that allows you to perform image processing and computer vision tasks. It provides a wide range of features, including object detection, face recognition, and tracking

In [3]:
import cv2 as cv
img = cv.imread("C:/Users/User7/Desktop/g.jpg")

cv.imshow("Display window", img)
k = cv.waitKey(0) # Wait for a keystroke in the window

KERAS FEATURES

In [1]:
#  PRELABELED DATASET
# import the keras pakage
from  keras.datasets import mnist 

#  NUMEROUS IMPLEMENTED LAYERS AND PARAMETERS
# import th eanother pakages
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.optimizers import Adam
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras import utils
import numpy as np
import np_utils


# MULTIPLE METHODS FRO DATA PREPROCESSING

# divide the  Data into (X_train ,Y_train,X_test,Y_test)
(X_train, y_train), (X_test, y_test) = mnist.load_data()


#reshape in form of (60000, 28, 28, 1)
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], X_train.shape[2], 1).astype('float32')
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], X_test.shape[2], 1).astype('float32')
#normalize to get data in range of 0-1
X_train/=255
X_test/=255
number_of_classes = 10
y_train = utils.to_categorical(y_train, number_of_classes)
y_test = utils.to_categorical(y_test, number_of_classes)


''' add() Method in Keras
To add layers imported above by specifying parameters to build
your digit classifier, it is done using .add() method.'''

model = Sequential()
model.add(Conv2D(32, (5, 5), input_shape=(X_train.shape[1], X_train.shape[2], 1), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(number_of_classes, activation='softmax'))

'''compile() Method in Keras
Before training, you need to configure your 
learning process which is done using .compile() method.'''

model.compile(loss='categorical_crossentropy', optimizer=Adam(), metrics=['accuracy'])

model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=5, batch_size=200) 
model.save("model.h5") 

Epoch 1/5
300/300 [==============================] - 27s 78ms/step - loss: 0.4712 - accuracy: 0.8501 - val_loss: 0.0931 - val_accuracy: 0.9718
Epoch 2/5
300/300 [==============================] - 22s 73ms/step - loss: 0.1574 - accuracy: 0.9531 - val_loss: 0.0534 - val_accuracy: 0.9820
Epoch 3/5
300/300 [==============================] - 21s 71ms/step - loss: 0.1201 - accuracy: 0.9635 - val_loss: 0.0419 - val_accuracy: 0.9856
Epoch 4/5
300/300 [==============================] - 22s 73ms/step - loss: 0.1013 - accuracy: 0.9692 - val_loss: 0.0385 - val_accuracy: 0.9867
Epoch 5/5
300/300 [==============================] - 22s 75ms/step - loss: 0.0877 - accuracy: 0.9738 - val_loss: 0.0323 - val_accuracy: 0.9886


c:\Users\User7\anaconda3\lib\site-packages\keras\src\engine\training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


MODEL EVALUATION

In [2]:
'''compile() Method in Keras
Before training, you need to configure your learning process which is done using .compile() method
.'''

import cv2
img = cv2.imread("C:/Users/User7/Desktop/gourav.jpg", cv2.IMREAD_GRAYSCALE)
# resize image
resized = cv2.resize(img, (28,28), interpolation = cv2.INTER_AREA)
img = np.resize(resized, (28,28,1))
im2arr = np.array(img)
im2arr = im2arr.reshape(1,28,28,1)
y_pred = model.predict(im2arr)
predicted_digit=np.argmax(y_pred)
print(y_pred)
print(predicted_digit)


1/1 [==============================] - 0s 278ms/step
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]
8


HOT ENCODING

In [36]:
import numpy as np
from keras.utils import to_categorical

# Example categorical labels
labels = ['cat', 'dog', 'bird', 'dog', 'cat']

# Create a mapping of unique labels to numerical integers
label_to_int = {label: i for i, label in enumerate(set(labels))}

# Convert the string labels to numerical integer labels
numerical_labels = [label_to_int[label] for label in labels]

# Perform one-hot encoding on the numerical labels
encoded_labels = to_categorical(numerical_labels)

print(encoded_labels)


[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


REINFORCMENT LEARNING

In [8]:
import gym
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

# Create the CartPole environment
env = gym.make('CartPole-v1')

# Q-learning algorithm
def q_learning(env, episodes=1000, alpha=0.1, gamma=0.99, epsilon=0.1):
    n_actions = env.action_space.n
    n_states = env.observation_space.shape[0]
    q_table = np.zeros((n_states, n_actions))

    for episode in range(episodes):
        state = env.reset()
        done = False

        while not done:
            if np.random.rand() < epsilon:
                action = env.action_space.sample()
            else:
                action = np.argmax(q_table[state, :])
                # Assuming state_space_size and action_space_size are appropriate values for your environment
                # q_table = np.zeros((state, action))


            next_state, reward, done, _ = env.step(action)

            q_next = np.max(q_table[next_state, :])
            q_table[state, action] = (1 - alpha) * q_table[state, action] + alpha * (reward + gamma * q_next)

            state = next_state

    return q_table

# Train Q-learning agent
q_table = q_learning(env)

# Test the agent
state = env.reset()
done = False

while not done:
    action = np.argmax(q_table[state, :])
    next_state, _, done, _ = env.step(action)
    env.render()
    state = next_state

env.close()

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

Reinforcment learning

In [10]:
#  : Training an image classifier from scratch on the Kaggle Cats vs Dogs dataset.
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense

# Generate synthetic timeseries data
def generate_timeseries_data(n_steps):
    time = np.linspace(0, 2*np.pi, n_steps)
    data = np.sin(time) + np.random.normal(0, 0.1, n_steps)
    return data

n_steps = 100
data = generate_timeseries_data(n_steps)

# Prepare data for LSTM (input and target)
X = data[:-1]
y = data[1:]


# Reshape data for LSTM (samples, timesteps, features)
X = X.reshape(-1, 1, 1)

# Create LSTM model
model = Sequential()
model.add(LSTM(32, input_shape=(1, 1)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

# Train the model
model.fit(X, y, epochs=100, batch_size=1)

Epoch 1/100
99/99 [==============================] - 1s 1ms/step - loss: 0.4280
Epoch 2/100
99/99 [==============================] - 0s 1ms/step - loss: 0.2304
Epoch 3/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0788
Epoch 4/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0241
Epoch 5/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0190
Epoch 6/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0188
Epoch 7/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0190
Epoch 8/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0189
Epoch 9/100
99/99 [==============================] - 0s 2ms/step - loss: 0.0192
Epoch 10/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0191
Epoch 11/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0192
Epoch 12/100
99/99 [==============================] - 0s 1ms/step - loss: 0.0194
Epoch 13/100
99/99 [=================